app:
  card-expiration-years: 3
  max-transfer-amount: 500000

server:
  port: 9999
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://db:5432/bankdb
    username: bank-rest
    password: bank-rest-password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/migration/master.yaml
    enabled: true

jwt:
  secret: BankCardsSecureKey2024_a8f3j2k9m5n7p1q4r6s8t0u2v4w6x8y0
  expiration: 3600000
