-- changelog Adis: 002 create user table
CREATE TABLE USERS (
    ID              BIGSERIAL PRIMARY KEY,
    NAME            VARCHAR(100),
    SURNAME         VARCHAR(100),
    EMAIL           VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD        VARCHAR(255) NOT NULL,
    ENABLED         BOOLEAN NOT NULL DEFAULT TRUE,
    AUTHORITIES_ID  INTEGER,

    CONSTRAINT FK_USER_AUTHORITIES
        FOREIGN KEY (AUTHORITIES_ID)
        REFERENCES AUTHORITIES (ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);