-- changelog Adis: 003 create card table
CREATE TABLE CARDS (
    ID                 BIGSERIAL PRIMARY KEY,
    BALANCE            NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    OWNER_ID           INTEGER,
    CARD_NUMBER        VARCHAR(16) UNIQUE NOT NULL,
    EXPIRATION_DATE    TIMESTAMP DEFAULT CURRENT_DATE,

    CONSTRAINT FK_CARD_OWNER
        FOREIGN KEY (OWNER_ID)
        REFERENCES USERS (ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);
